// Package renderer generates Terraform HCL configurations from resolved module mappings.
package renderer

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/openseam/generators/terraform/internal/resolver"
)

const mainTFTemplate = `# Generated by OpenSeam Terraform Blueprint Generator
# Application: {{.AppName}}
# Provider:    {{.Provider}}

terraform {
  required_version = ">= 1.5"
  required_providers {
    {{- if eq .Provider "aws"}}
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    {{- else if eq .Provider "gcp"}}
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
    {{- else if eq .Provider "azure"}}
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    {{- end}}
  }
}

{{- if eq .Provider "aws"}}
provider "aws" {
  region = var.aws_region
}
{{- else if eq .Provider "gcp"}}
provider "google" {
  project = var.gcp_project
  region  = var.gcp_region
}
{{- else if eq .Provider "azure"}}
provider "azurerm" {
  features {}
}
{{- end}}

{{range .Modules}}
module "{{.Name}}" {
  source = "{{.Source}}"
{{- range $k, $v := .Vars}}
  {{$k}} = "{{$v}}"
{{- end}}
}
{{end}}`

const variablesTFTemplate = `variable "{{.Provider}}_region" {
  description = "Deployment region"
  type        = string
  default     = "us-east-1"
}
`

// Blueprint holds the generated Terraform files for a provider.
type Blueprint struct {
	Provider  string
	AppName   string
	MainTF    string
	Variables string
}

// Render produces Terraform HCL content for the given module mappings.
func Render(appName string, mappings []resolver.ModuleMapping) ([]Blueprint, error) {
	mainTmpl, err := template.New("main").Parse(mainTFTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing main.tf template: %w", err)
	}

	varTmpl, err := template.New("vars").Parse(variablesTFTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing variables.tf template: %w", err)
	}

	var blueprints []Blueprint
	for _, mapping := range mappings {
		data := struct {
			AppName  string
			Provider string
			Modules  []resolver.TerraformModule
		}{
			AppName:  appName,
			Provider: mapping.Provider,
			Modules:  mapping.Modules,
		}

		var mainBuf bytes.Buffer
		if err := mainTmpl.Execute(&mainBuf, data); err != nil {
			return nil, fmt.Errorf("rendering main.tf for %s: %w", mapping.Provider, err)
		}

		var varBuf bytes.Buffer
		if err := varTmpl.Execute(&varBuf, data); err != nil {
			return nil, fmt.Errorf("rendering variables.tf for %s: %w", mapping.Provider, err)
		}

		blueprints = append(blueprints, Blueprint{
			Provider:  mapping.Provider,
			AppName:   appName,
			MainTF:    mainBuf.String(),
			Variables: varBuf.String(),
		})
	}

	return blueprints, nil
}
